### ISSUE TITLE
Shutdown Pi/Stop Recording

### ISSUE THREAD

**Issue by ursius2020** [notchum/dashcam#1]
I realy like the idea to use a Pi Zero as a dashcam, but i think there Is a small Problem.

So if i would use it in my car the Pi Boots up when i start the Engine and starts recording. But how can i stop the recording after i arrived or after a real car accident?
How can i savely power done the Pi to Not dammage the SD Card or USB Drive?
I have already destroyed a sd card by unplugging the Pi (3B+ instead of Zero but does Not matter) without Shutdown…

Mounting with a 3dprinted holder is clear to me and also Power from my cigaret lighter but i See no way to switch it off other then pull the Plug

**Comment by RT3K** [comment]
You can add a Power button to the pi and write a little script to shutdown when pressing the Button.

**Comment by notchum** [comment]
A power button could work but, in essence, it would be accomplishing the same thing as an unplug.

From the README:
> The recordings are initially recording with an .h264 extension and once the designated video length is reached the script convert the video to .mp4. This works pretty well but if the Pi is turned off mid-recording, then the latest file will still have that .h264 extension, so take note of that.

If you are using a USB drive, as the project outlines, then simply unplugging the USB drive from the Pi will have the video files there - the only exception being they _may_ be in a .h264 format. This isn't a big deal, since you could use FFmpeg, VLC, or some other converter to get it into a .mp4 format for convenience.

**Comment by notchum** [comment]
Oh, I misread @RT3K's comment. Yes a script would be a smart way of doing this.
