### ISSUE TITLE
USB or SDCard?

### ISSUE THREAD

**Issue by candiesdoodle** [notchum/dashcam#3]
Hello, based on the pictures you have posted on imgur it seems there is a slot for a USB stick as well there is a SDCard inserted where the GPS module is. Could you confirm if i am reading it correct from the pictures? I understand like you mentioned about the read write errors on SDCard and hence a USB stick might be better, but just trying to figure out the setup in the pictures first. thanks!

**Comment by notchum** [comment]
I used a USB flash drive for this project, yes. The Raspi Zero W only has two Micro-USB ports, though (and one is for powering the Pi). Therefore, I got an adapter so that I could use a proper USB stick - here's the one I got:
https://www.digikey.com/en/products/detail/COM-14567/1568-1821-ND/8324538?so=62943201
